services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        networks:
            - net

    myadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        networks:
            - net

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        networks:
            - net

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
        networks:
            - net

    front:
        stdin_open: true
        build:
            context: ./playlistyoutubeapp
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - "app/node_modules"
            - "./playlistyoutubeapp:/app"
        networks:
            - net

    backend:
        build:
            context: ./node
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - net
        restart: on-failure
        environment:
            - MYSQL_HOST=db
            - URL_MONGO=mongodb
        depends_on:
            - db
            - mongo

networks:
    net:
        driver: bridge
