services:
    front:
        stdin_open: true
        build:
            context: ./playlistyoutubeapp
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - "app/node_modules"
            - "./playlistyoutubeapp:/app"
        networks:
            - net

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        cap_add:
            - SYS_NICE # CAP_SYS_NICE
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - net

    myadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        networks:
            - net

    backend:
        build:
            context: ./node
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - net
        restart: always
        environment:
            - MYSQL_HOST=db
        depends_on:
            - db

    mongodb:
        image: mongo
        container_name: mongodb
        hostname: mongodb
        restart: always
        ports:
            - "27017:27017"
        networks:
            - net

    mongo-express:
        image: mongo-express
        restart: always
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - 8081:8081
        networks:
            - net

    backendmongo:
        build:
            context: ./nodemongo
            dockerfile: Dockerfile
        ports:
            - "5001:5001"
        networks:
            - net
        restart: on-failure
        environment:
            - URL_MONGO=mongodb
        depends_on:
            - mongodb

networks:
    net:
        driver: bridge
